<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SoftwareFactory.FactoryBot-76116897-fd1d-4384-8338-a37a1ed2c82d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="Telegram.Bot" Version="22.10.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SoftwareFactory.FactoryBot.Tests" />
  </ItemGroup>
</Project>
