/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploymentEventDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnalyticsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateClientRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/options.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePhaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/projects/{id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApprovalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalGateDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectUsageDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUsageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiUsageRecordDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploymentEventDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDeploymentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploymentEventDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntakeCatalogDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyticsDto: {
            /** Format: uuid */
            projectId: string;
            provider: string;
            /** Format: int64 */
            visitors: number;
            /** Format: int64 */
            pageViews: number;
            /** Format: double */
            bounceRate: number;
            timeseries: components["schemas"]["AnalyticsTimeseriesPointDto"][];
        };
        AnalyticsTimeseriesPointDto: {
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            visitors: number;
            /** Format: int64 */
            pageViews: number;
        };
        ApiUsageRecordDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            model: string;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            costUsd: number;
            /** Format: date-time */
            recordedAt: string;
        };
        ApprovalGateDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            gateType: components["schemas"]["GateType"];
            approvedBy: string | null;
            /** Format: date-time */
            approvedAt: string | null;
            notes: string | null;
            isApproved: boolean;
        };
        ClientDto: {
            /** Format: uuid */
            id: string;
            name: string;
            contactEmail: string | null;
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateApprovalRequest: {
            gateType: components["schemas"]["GateType"];
            approvedBy: string;
            notes: string | null;
        };
        CreateClientRequest: {
            name: string;
            contactEmail: string | null;
            notes: string | null;
        };
        CreateDeploymentRequest: {
            status: components["schemas"]["DeploymentStatus"];
            source: components["schemas"]["DeploymentSource"];
            payload: string | null;
        };
        CreateProjectRequest: {
            /** Format: uuid */
            clientId: string | null;
            name: string;
            siteType: string;
            repoUrl: string | null;
            branch: string | null;
            intake?: components["schemas"]["ProjectIntakeRequest"];
        };
        CreateUsageRequest: {
            model: string;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            costUsd: number;
        };
        DeploymentEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            status: components["schemas"]["DeploymentStatus"];
            source: components["schemas"]["DeploymentSource"];
            payload: string;
            /** Format: date-time */
            occurredAt: string;
        };
        /** @enum {unknown} */
        DeploymentSource: "ci" | "manual";
        /** @enum {unknown} */
        DeploymentStatus: "pending" | "success" | "failure";
        /** @enum {unknown} */
        GateType: "architecture" | "security" | "deploy";
        IntakeCatalogDto: {
            market: string;
            currency: string;
            languages: string[];
            designDirections: string[];
            payments: string[];
            integrations: string[];
            features: string[];
            siteTypes: components["schemas"]["IntakeSiteTypeDto"][];
        };
        IntakeSectionOptionDto: {
            key: string;
            core: boolean;
            /** Format: int32 */
            order: number;
        };
        IntakeSiteTypeDto: {
            siteType: string;
            sections: components["schemas"]["IntakeSectionOptionDto"][];
            recommendedIntegrations: string[];
        };
        ProjectDetailDto: {
            project: components["schemas"]["ProjectDto"];
            gates: components["schemas"]["ApprovalGateDto"][];
            usage: components["schemas"]["ProjectUsageDto"];
            recentDeployments: components["schemas"]["DeploymentEventDto"][];
            intake?: components["schemas"]["ProjectIntakeDto"];
            /** @default null */
            optionsJson: string | null;
        };
        ProjectDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientId: string;
            name: string;
            siteType: string;
            currentPhase: components["schemas"]["ProjectPhase"];
            repoUrl: string | null;
            branch: string | null;
            liveUrl: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @default null */
        ProjectIntakeDto: {
            clientName: string;
            clientContact: string;
            language: string;
            defaultDirection: string;
            designDirection: string;
            sections: string[];
            payments: string[];
            integrations: string[];
            features: string[];
            notes: string | null;
        } | null;
        /** @default null */
        ProjectIntakeRequest: {
            clientName: string | null;
            clientContact: string | null;
            language: string | null;
            designDirection: string | null;
            sections: string[] | null;
            /** @default null */
            payments: string[] | null;
            /** @default null */
            integrations: string[] | null;
            /** @default null */
            features: string[] | null;
            /** @default null */
            notes: string | null;
        } | null;
        /** @enum {unknown} */
        ProjectPhase: "intake" | "foundation" | "generation" | "build" | "harden" | "ship" | "operate";
        ProjectUsageDto: {
            records: components["schemas"]["ApiUsageRecordDto"][];
            /** Format: double */
            totalCostUsd: number;
            /** Format: int64 */
            totalTokens: number;
        };
        UpdatePhaseRequest: {
            phase: components["schemas"]["ProjectPhase"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
